
FROM python:3.9-slim-buster


WORKDIR /app

COPY frontmain.py .
COPY requirements.txt .


RUN pip install  -r requirements.txt





EXPOSE 8501


CMD ["streamlit", "run", "frontmain.py", "--server.port", "8501","0.0.0.0"]
